#!/bin/sh
# This shell script is responsible for showing the big machine name banners you see on login with ssh.
# To add this to a new machine, replace line 19 of this script with the ascii art you want to have shown.
# Afterwards, modify the color of your art with the prinf statement in line 15.
# Copy the resulting file to /etc/update-motd.d/ and reconnect with ssh. You should now see the ascii art printed on login!

# Troubleshooting:
# Run
# sudo run-parts /etc/update-motd.d/
# to see any error messages that might appear.

printf '\n You are currently on:\n'

#change color: (Color reference: https://opensource.com/article/19/9/linux-terminal-colors )
printf '\033[32m'

#Print machine name (ascii art generated by: https://textkool.com/en/ascii-art-generator?hl=default&vl=default&font=ANSI Shadow )
printf '
>>>>Insert machine name ascii art here!<<<< (If you are confused whats happening here, read the comments of this file) '
printf '\033[39m\n' #Change color back to default