stages:
  - pre
  - build
  - post

artifacts:
  stage: build
  tags: [ shell, dev ]
  script:
    - make artifacts
  artifacts:
    public: true
    paths:
      - powershell-modules/powershell-modules.zip
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - powershell-modules/powershell-modules.zip.files

include:
  - project: mdctec-developers/internal/maintenance-menu
    file: 'push-to-menu.yml'

Push Menu Config:
  extends:
    - .deploy config for menu
  stage: pre
  tags:
    - dev
    - docker

#build_turnserver_image:
#  stage: build
#  tags:
#    - dev
#    - shell #maybe use crane?
#  script:
#    - echo "TODO" #TODO
#  only:
#    changes:
#      - machines/TURN-Server/turnserver.conf


