stages:
  - artifacts

artifacts:
  stage: artifacts
  tags: [ shell, stage ]
  script:
    - make artifacts
  artifacts:
    public: true
    paths:
      - machines/**/*.sh
      - scripts/bash/*.sh
      - scripts/powershell/MdctecMaintenance/MdctecMaintenance.zip

artifacts_dev:
  extends: artifacts
  tags: [ shell, dev ]
