stages:
  - pre
  - build
  - post

artifacts:
  stage: build
  tags: [ shell, dev ]
  script:
    - make artifacts
  artifacts:
    public: true
    paths:
      - scripts/powershell-modules/powershell-modules.zip
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - scripts/powershell-modules/powershell-modules.zip.files
      -
#build_turnserver_image:
#  stage: build
#  tags:
#    - dev
#    - shell #maybe use crane?
#  script:
#    - echo "TODO" #TODO
#  only:
#    changes:
#      - machines/TURN-Server/turnserver.conf





        #mdctec-maintenance:
#  stage: build
#  tags: [ shell, dev ]
#  script:
#    - make -C docker/mdctec-maintenance build
#  artifacts:
#    paths:
#      - docker/mdctec-maintenance/build
#  cache:
#    key: $CI_COMMIT_REF_SLUG
#    paths:
#      - scripts/powershell-modules/powershell-modules.zip.files
#push:
#  stage: post
#  tags: [ shell, dev ]
#  script:
#    - make -C docker/mdctec-maintenance push
