.default:
  when: manual


.wstage:
  extends: .default
  tags: [wstage, shell]

wstage scan:
  extends: .wstage
  script:
    - docker system df
    - Get-PSDrive

wstage cleanup:
  extends: .wstage
  script:
    - docker volume prune -f
    - docker system prune -af

.dev:
  extends: .default
  tags: [dev, shell]

dev scan:
  extends: .dev
  script: 
    - docker system df
    - du -h / 2>/dev/nul | sort -h

dev cleanup:
  extends: .dev
  script:
    - docker exec registry registry garbage-collect /path/to/your/registry/config.yml --delete-untagged=true
    - docker volume prune -f
    - docker system prune -af
