stages:
  - build

# download link:
# http://gitlab.mdctec.com/mdctec-developers/internal/infrastructure/-/jobs/artifacts/master/raw/scripts/MdctecMaintainance/MdctecMaintainance.zip?job=zip_MdctecMaintainance_module
# http://gitlab.mdctec.com/mdctec-developers/internal/infrastructure/-/jobs/artifacts/master/browse/scripts/MdctecMaintanance.zip?job=zip_MdctecMaintainance_module
zip_MdctecMaintanance_module:
  stage: build
  script:
    - cd scripts/MdctecMaintainance
    - zip -r MdctecMaintainance.zip .
  tags:
    - stage.mdctec.com
  artifacts:
    paths:
      - scripts/MdctecMaintainance/MdctecMaintainance.zip
