stages:
  - build

zip_MdctecMaintanance_module:
  stage: build
  script:
    - cd scripts/MdctecMaintanance
    - zip -r MdctecMaintanance.zip .
  tags:
    - stage.mdctec.com
  artifacts:
    paths:
      - scripts/MdctecMaintanance.zip
