stages:
  - artifacts

# download links:
#
# Direct download:
# http://gitlab.mdctec.com/mdctec-developers/internal/infrastructure/-/jobs/artifacts/master/raw/scripts/MdctecMaintenance/MdctecMaintenance.zip?job=zip_MdctecMaintenance_module

#zip_MdctecMaintenance_module:
#  stage: artifacts
#  before_script:
#    - cd scripts/powershell/MdctecMaintenance
#  script:
#    - make MdctecMaintencance.zip
#  tags:
#    - stage.mdctec.com

artifacts:
  stage: artifacts
  public: true
  script: [echo "preparing artifacts..."]
  artifacts:
    paths:
      - machines/**/*.sh
      - scripts/bash/*.sh


include:
  - /scripts/powershell/MdctecMaintenance/.gitlab-ci.yml
