stages:
  - build

zip_MdctecMaintainance_module:
  stage: build
  script:
    - cd scripts/MdctecMaintainance
    - zip -r MdctecMaintainance.zip .
  tags:
    - stage.mdctec.com
  artifacts:
    paths:
      - scripts/MdctecMaintainance/MdctecMaintainance.zip
