stages:
  - artifacts

#devcontainer:
#  stage: artifacts
#  rules:
#    - changes:
#        - .docker/devcontainer.Dockerfile
#  tags: [ shell, dev ]
#  script:
#    - docker-compose build devcontainer

artifacts:
  stage: artifacts
  tags: [ shell, dev ]
  script:
    - make artifacts
  artifacts:
    public: true
    paths:
      - machines/**/*.sh
      - scripts/bash/*.sh
      - scripts/powershell-modules/powershell-modules.zip
