stages:
  - artifacts

artifacts:
  stage: artifacts
  script:
    - make artifacts
  artifacts:
    public: true
    paths:
      - machines/**/*.sh
      - scripts/bash/*.sh
      - scripts/powershell/MdctecMaintenance/MdctecMaintenance.zip
