stages:
  - artifacts

devcontainer:
  rules:
    - changes:
        - .docker/devcontainer.Dockerfile
  tags: [ shell, dev ]
  script:
    - docker-compose build devcontainer

artifacts:
  stage: artifacts
  image: infrastructure/devcontainer
  tags: [ docker, dev ]
  script:
    - make artifacts
  artifacts:
    public: true
    paths:
      - machines/**/*.sh
      - scripts/bash/*.sh
      - scripts/powershell-modules/MdctecMaintenanceMenu.zip
