stages:
  - build

# download links:
#
# Direct download:
# http://gitlab.mdctec.com/mdctec-developers/internal/infrastructure/-/jobs/artifacts/master/raw/scripts/MdctecMaintenance/MdctecMaintenance.zip?job=zip_MdctecMaintenance_module

zip_MdctecMaintenance_module:
  stage: build
  script:
    - cd scripts/powershell/MdctecMaintenance
    - zip -r MdctecMaintenance.zip .
  tags:
    - stage.mdctec.com
  artifacts:
    paths:
      - scripts/powershell/MdctecMaintenance/MdctecMaintenance.zip
