stages:
  - build

zip_MdctecMaintanance_module:
  stage: build
  script:
    - cd scripts
    - zip -r MdctecMaintanance.zip ./MdctecMaintainance
  tags:
    - stage.mdctec.com
  artifacts:
    paths:
      - scripts/MdctecMaintanance.zip
