version: "3.8"
services:
  devcontainer:
    image: infrastructure/devcontainer
    build: docker/devcontainer

  mdctec-maintenance:
    image: infrastructure/mdctec-maintenance:latest
    build:
      context: .
      dockerfile: powershell-modules/.docker/Dockerfile
