groups:
  - name: alerts
    rules:

    #Alert if any server goes down for more than 5 minutes
    - alert: upcheck
      expr: up == 0
      for: 5m
      annotations:
        summary: "{{$labels.job}} is down!"
        description: "{{$labels.job}} could not be reached, please investigate."
    # Alert if any server does not respond with 200 as a status code
    - alert: http_status_ok
      expr: probe_http_status_code != 200
      for: 2m
      annotations:
        summary: "{{$labels.instance}} is not healthy!"
        description: "{{$labels.instance}} responded with status code {{$value}} multiple times in the last 2 minutes."
    # Alert if any server has a higher response time than 2 seconds
    - alert: http_response_time
      expr: probe_duration_seconds > 2
      for: 5m
      annotations:
        summary: "${{$labes.instance}} has abnormal response time!"
        description: "{{$labes.instance}} responded after {{$value}} seconds. The response time should be below 2 seconds!"
