groups:
  # All alerts related to the server itself
  - name: machines
    rules:
    #Alert if any server goes down for more than 5 minutes
    - alert: up_check_ok
      expr: up == 0
      for: 5m
      annotations:
        summary: "{{$labels.job}} is down!"
        description: "{{$labels.job}} could not be reached, please investigate."
      labels:
        severity: critical
    # Warn if the server has less than 30% disk space remaining
    - alert: disk_nearly_full
      expr: ((node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) or (node_filesystem_free{mountpoint="/"} / node_filesystem_size{mountpoint="/"})) < 0.3
      for: 30m
      annotations:
        summary: "{{$labels.job}} is running full!"
        description: "$${labels.job} has less than 30% of disk storage space remaining! Please clean up. Current value: {{ $value}}"
      labels:
        severity: medium
    # Alert if the server has less than 5% disk space remaining
    - alert: disk_full
      expr: ((node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) or (node_filesystem_free{mountpoint="/"} / node_filesystem_size{mountpoint="/"})) < 0.05
      for: 30m
      annotations:
        summary: "{{$labels.job}} is nearly full!"
        description: "$${labels.job} has less than 5% of disk storage space remaining! Please clean up. Current value: {{$value}}"
      labels:
        severity: critical
    - alert: swap_to_high
      expr: (((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes) or ((node_memory_SwapTotal - node_memory_SwapFree) / node_memory_SwapTotal)) > 0.15
      for: 5m
      annotations:
        summary: "{{$labels.job}} is using a lot of RAM!"
        description: "$${labels.job} is using more than 15% of its currently available swap. Increasing RAM is recommended. Current value: {{$value}}"
      labels:
        severity: medium
    - alert: swap_crititcaly_high
      expr: (((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes) or ((node_memory_SwapTotal - node_memory_SwapFree) / node_memory_SwapTotal)) > 0.7
      for: 5m
      annotations:
        summary: "{{$labels.job}} is using way to much RAM!"
        description: "$${labels.job} is using more than 70% of its currently available swap. Increasing RAM is recommended. Current value: {{$value}}"
      labels:
        severity: high

  # All alerts related to data collected by the blackbox exporter
  - name: blackbox
    rules:
      # Alert if any server does not respond with 200 as a status code
    - alert: http_status_ok
      expr: probe_http_status_code != 200
      for: 2m
      annotations:
        summary: "{{$labels.instance}} is not healthy!"
        description: "{{$labels.instance}} responded with status code {{$value}} multiple times in the last 2 minutes."
      labels:
        severity: critical

      # Alert if any server has a higher response time than 2 seconds
    - alert: http_response_time
      expr: probe_duration_seconds > 2
      for: 5m
      annotations:
        summary: "${{$labels.instance}} has abnormal response time!"
        description: "{{$labels.instance}} responded after {{$value}} seconds. The response time should be below 2 seconds!"
      labels:
        severity: medium
