services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  alertmanager:
    image: quay.io/prometheus/alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus:/etc/alertmanager


volumes:
  prometheus_data: