global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/**

scrape_configs:
  - job_name: stage_server
    static_configs:
      - targets: ['stage.mdctec.com:9100']
  - job_name: chemprofiler_server
    static_configs:
      - targets: ['node-exporter.chemprofiler.mdctec.com:9100']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx ]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - http://master.chemprofiler.mdctec.com/ # Target the master deployment of the chemprofiler
          - http://invalid.chemprofiler.mdctec.com/ # Target an invalid deployment of the chemprofiler
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.