global:
  scrape_interval: 15s

scrape_configs:
  - job_name: stage_server
    static_configs:
      - targets: ['stage.mdctec.com:9100']
  - job_name: chemprofiler_server
    static_configs:
      - targets: ['node-exporter.chemprofiler.mdctec.com:9100']